<?php declare(strict_types = 1);

namespace App\UI\Modules\Front;

use App\Model\Utils\Config;
use App\UI\Modules\Base\UnsecuredPresenter;

abstract class BaseFrontPresenter extends UnsecuredPresenter
{
    /**
     * @var Config
     * @inject
     */
    public Config $config;

    protected function beforeRender()
    {
        $this->template->config = $this->config;
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }

}
